### ISSUE TITLE
Simple and extreme high-speed alternative to universal markdown lib

### ISSUE THREAD

**Issue by Opiumtm** [10UWP/The-UWP-Tools-List#1]
https://www.nuget.org/packages/Ipatov.MarkupRender/

Markup rendering engine based on Direct2D instead of XAML tree manipulations.
First public release is very simplistic and not feature rich, but most important feature of this library is very high performance.

**Comment by 10Dev** [comment]
IpatovUWP project updated with your information in UWP Libs section
